"""Add profit detail fields to ledger entries

Revision ID: add_profit_detail_fields
Revises: b5bc6a6c2693
Create Date: 2025-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_profit_detail_fields'
down_revision = 'b5bc6a6c2693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_entries', sa.Column('profit_before', sa.Float(), nullable=True))
    op.add_column('ledger_entries', sa.Column('profit_after', sa.Float(), nullable=True))
    op.add_column('ledger_entries', sa.Column('profit_change', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ledger_entries', 'profit_change')
    op.drop_column('ledger_entries', 'profit_after')
    op.drop_column('ledger_entries', 'profit_before')
    # ### end Alembic commands ###


