"""Add transfer columns to ledger_entries

Revision ID: add_transfer_columns
Revises: add_fifo_tables
Create Date: 2025-01-27 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_transfer_columns'
down_revision = 'add_fifo_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 刪除所有重複的 op.add_column 語句 (針對 ledger_entries 表)
    # op.add_column('ledger_entries', sa.Column('from_account_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(op.f('fk_ledger_entries_from_account_id_cash_accounts'), 'ledger_entries', 'cash_accounts', ['from_account_id'], ['id'])
    # op.add_column('ledger_entries', sa.Column('to_account_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(op.f('fk_ledger_entries_to_account_id_cash_accounts'), 'ledger_entries', 'cash_accounts', ['to_account_id'], ['id'])
    # op.add_column('ledger_entries', sa.Column('profit_before', sa.Numeric(precision=10, scale=2), nullable=True))
    # op.add_column('ledger_entries', sa.Column('profit_after', sa.Numeric(precision=10, scale=2), nullable=True))
    # op.add_column('ledger_entries', sa.Column('profit_change', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###
    pass # 保持原樣或註釋掉，讓 Cursor 執行修正。


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('ledger_entries', 'profit_change')
    # op.drop_column('ledger_entries', 'profit_after')
    # op.drop_column('ledger_entries', 'profit_before')
    # op.drop_constraint(op.f('fk_ledger_entries_to_account_id_cash_accounts'), 'ledger_entries', type_='foreignkey')
    # op.drop_column('ledger_entries', 'to_account_id')
    # op.drop_constraint(op.f('fk_ledger_entries_from_account_id_cash_accounts'), 'ledger_entries', type_='foreignkey')
    # op.drop_column('ledger_entries', 'from_account_id')
    # ### end Alembic commands ###
    pass
